# https://docs.docker.com/compose/compose-file/compose-versioning/
# Nous utilisons la version 3.8 car notre moteur Docker est supérieur à la version 19.03.0+
# https://docs.gitlab.com/omnibus/docker/
version: "3.8"
services: 
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.12.0'
    # restart: always
    # hostname: 'gitlab.devops.oc'
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    #   - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
        memlock:
          soft: -1
          hard: -1
    ports:
      - '9200:9200'      
    # networks:
    #     - elastic
    # volumes:
    #   - '${GITLAB_HOME}/config:/etc/gitlab'
    #   - '${GITLAB_HOME}/logs:/var/log/gitlab'
    #   - '${GITLAB_HOME}/data:/var/opt/gitlab'
    # container_name: gitlab-ee

  # https://www.elastic.co/guide/en/kibana/current/docker.html#configuring-kibana-docker
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.12.0'
    ports:
        - '5601:5601'
    depends_on: ['elasticsearch'] 
